In [1]:
# Required Libraries
import pandas as pd
import numpy as np

In [2]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\Dell\AppData\Local\Programs\Python\Python312\Lib\site-packages (26.7.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Dell\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [3]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\Users\Dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import mysql.connector

In [5]:
# connection Create
Connection = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = 'JaiMata@21',
    database = 'ecommerce_analytics'
)

In [6]:
print(Connection.is_connected())

True

In [7]:
# Cuesor Create
cursor = Connection.cursor()

In [8]:
# 1. Correct the table name to 'customers'
Query = "SELECT * from customers Limit 10"

# 2. Create the cursor object
cursor = Connection.cursor()

# 3. Execute the query (This tells the database to actually run it)
cursor.execute(Query)

# 4. fetch  results
result = cursor.fetchall()
result

[('C0001',
  'Customer_0001',
  'Male',
  34,
  'Mumbai',
  'West',
  datetime.date(2023, 1, 21)),
 ('C0002',
  'Customer_0002',
  'Female',
  26,
  'Hyderabad',
  'South',
  datetime.date(2025, 9, 10)),
 ('C0003',
  'Customer_0003',
  'Male',
  50,
  'Pune',
  'West',
  datetime.date(2023, 11, 1)),
 ('C0004',
  'Customer_0004',
  'Male',
  37,
  'Bengaluru',
  'South',
  datetime.date(2024, 1, 6)),
 ('C0005',
  'Customer_0005',
  'Male',
  30,
  'Chennai',
  'South',
  datetime.date(2025, 5, 2)),
 ('C0006',
  'Customer_0006',
  'Female',
  45,
  'Jaipur',
  'North',
  datetime.date(2024, 1, 19)),
 ('C0007',
  'Customer_0007',
  'Male',
  46,
  'Lucknow',
  'North',
  datetime.date(2024, 3, 20)),
 ('C0008',
  'Customer_0008',
  'Male',
  30,
  'Bengaluru',
  'South',
  datetime.date(2024, 2, 29)),
 ('C0009',
  'Customer_0009',
  'Male',
  52,
  'Hyderabad',
  'South',
  datetime.date(2023, 6, 10)),
 ('C0010',
  'Customer_0010',
  'Female',
  23,
  'Ahmedabad',
  'West',
  datetime.date(2024, 9, 20))]

In [9]:
Customers = pd.read_sql('select * from Customers',Connection)

C:\Users\Dell\AppData\Local\Temp\ipykernel_28556\3402267.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Customers = pd.read_sql('select * from Customers',Connection)

In [10]:
Customers.head()

  CustomerID   CustomerName  Gender  Age       City Region  SignupDate
0      C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1      C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2      C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3      C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4      C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [11]:
Customers.shape

(1000, 7)

In [12]:
Customers.columns

Index(['CustomerID', 'CustomerName', 'Gender', 'Age', 'City', 'Region',
       'SignupDate'],
      dtype='str')

In [13]:
orders = pd.read_sql(
    'SELECT * from orders',Connection
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_28556\3702296848.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orders = pd.read_sql(

In [14]:
orders.head()

  OrderID   OrderDate CustomerID PaymentMethod OrderStatus
0  O00001  2026-01-19      C0484           UPI   Delivered
1  O00002  2026-02-14      C0450   Credit Card   Delivered
2  O00003  2025-11-21      C0523   Credit Card   Delivered
3  O00004  2025-05-08      C0871           UPI   Delivered
4  O00005  2025-05-04      C0354   Net Banking   Delivered

In [15]:
orders.shape

(5000, 5)

In [16]:
orders.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'PaymentMethod', 'OrderStatus'], dtype='str')

In [17]:
products = pd.read_sql(
    'SELECT * FROM products',Connection
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_28556\4185917707.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products = pd.read_sql(

In [18]:
products.head()

  ProductID          ProductName     Category  CostPrice  SellingPrice
0     P0001  Wireless Headphones  Electronics     4840.0        8847.0
1     P0002  Wireless Headphones  Electronics     4745.0        8892.0
2     P0003  Wireless Headphones  Electronics      262.0         319.0
3     P0004          Smart Watch  Electronics     2528.0        3517.0
4     P0005          Smart Watch  Electronics      289.0         526.0

In [19]:
orderdetails = pd.read_sql(
    'SELECT * FROM orderdetails', Connection
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_28556\127318964.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  orderdetails = pd.read_sql(

In [20]:
orderdetails.head()

,OrderDetailID,OrderID,ProductID,Quantity,UnitPrice,DiscountPct,SalesAmount,Profit
0,OD000001,O00001,P0014,4,10018.0,15.0,34061.20,12649.20
1,OD000002,O00001,P0063,3,5568.0,5.0,15868.80,6532.80
2,OD000003,O00002,P0030,1,10331.0,5.0,9814.45,3909.45
3,OD000004,O00002,P0027,4,4363.0,10.0,15706.80,2006.80
4,OD000005,O00003,P0040,2,6601.0,5.0,12541.90,4543.90

In [21]:
returns = pd.read_sql(
    'SELECT * FROM returns',Connection
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_28556\502769479.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  returns = pd.read_sql(

In [22]:
returns.head()

  ReturnID OrderID  ReturnDate   ReturnReason
0   R00001  O00016  1970-01-01        Damaged
1   R00002  O00078  1970-01-01  Wrong Product
2   R00003  O00088  1970-01-01     Size Issue
3   R00004  O00124  1970-01-01     Size Issue
4   R00005  O00125  1970-01-01  Late Delivery

In [23]:
print("Customers:", Customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Details:", orderdetails.shape)
print("Returns:", returns.shape)

Customers: (1000, 7)
Products: (82, 5)
Orders: (5000, 5)
Order Details: (12558, 8)
Returns: (257, 4)

In [24]:
query = """
SELECT 
    SUM(od.SalesAmount) AS TotalRevenue,
    SUM(od.Profit) AS TotalProfit
FROM Orders o
JOIN OrderDetails od
    ON o.OrderID = od.OrderID
WHERE o.OrderStatus = 'Delivered';
"""

In [25]:
revenue_summary = pd.read_sql(
    query,
    Connection
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_28556\4130569476.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  revenue_summary = pd.read_sql(

In [26]:
cursor.close()
Connection.close()

In [27]:
Customers.shape

(1000, 7)

In [28]:
products.shape

(82, 5)

In [29]:
returns.shape

(257, 4)

In [30]:
orderdetails.shape

(12558, 8)

In [31]:
orders.shape

(5000, 5)

In [32]:
Customers.head()

  CustomerID   CustomerName  Gender  Age       City Region  SignupDate
0      C0001  Customer_0001    Male   34     Mumbai   West  2023-01-21
1      C0002  Customer_0002  Female   26  Hyderabad  South  2025-09-10
2      C0003  Customer_0003    Male   50       Pune   West  2023-11-01
3      C0004  Customer_0004    Male   37  Bengaluru  South  2024-01-06
4      C0005  Customer_0005    Male   30    Chennai  South  2025-05-02

In [33]:
products.head()

  ProductID          ProductName     Category  CostPrice  SellingPrice
0     P0001  Wireless Headphones  Electronics     4840.0        8847.0
1     P0002  Wireless Headphones  Electronics     4745.0        8892.0
2     P0003  Wireless Headphones  Electronics      262.0         319.0
3     P0004          Smart Watch  Electronics     2528.0        3517.0
4     P0005          Smart Watch  Electronics      289.0         526.0

In [34]:
orders.head()

  OrderID   OrderDate CustomerID PaymentMethod OrderStatus
0  O00001  2026-01-19      C0484           UPI   Delivered
1  O00002  2026-02-14      C0450   Credit Card   Delivered
2  O00003  2025-11-21      C0523   Credit Card   Delivered
3  O00004  2025-05-08      C0871           UPI   Delivered
4  O00005  2025-05-04      C0354   Net Banking   Delivered

In [35]:
orderdetails.head()

,OrderDetailID,OrderID,ProductID,Quantity,UnitPrice,DiscountPct,SalesAmount,Profit
0,OD000001,O00001,P0014,4,10018.0,15.0,34061.20,12649.20
1,OD000002,O00001,P0063,3,5568.0,5.0,15868.80,6532.80
2,OD000003,O00002,P0030,1,10331.0,5.0,9814.45,3909.45
3,OD000004,O00002,P0027,4,4363.0,10.0,15706.80,2006.80
4,OD000005,O00003,P0040,2,6601.0,5.0,12541.90,4543.90

In [36]:
returns.head()

  ReturnID OrderID  ReturnDate   ReturnReason
0   R00001  O00016  1970-01-01        Damaged
1   R00002  O00078  1970-01-01  Wrong Product
2   R00003  O00088  1970-01-01     Size Issue
3   R00004  O00124  1970-01-01     Size Issue
4   R00005  O00125  1970-01-01  Late Delivery

In [37]:
Customers.dtypes

CustomerID         str
CustomerName       str
Gender             str
Age              int64
City               str
Region             str
SignupDate      object
dtype: object

In [38]:
orderdetails.dtypes

OrderDetailID        str
OrderID              str
ProductID            str
Quantity           int64
UnitPrice        float64
DiscountPct      float64
SalesAmount      float64
Profit           float64
dtype: object

In [39]:
orders.dtypes

OrderID             str
OrderDate        object
CustomerID          str
PaymentMethod       str
OrderStatus         str
dtype: object

In [40]:
orders["OrderDate"]=pd.to_datetime(orders["OrderDate"])

In [41]:
orders.dtypes

OrderID                    str
OrderDate        datetime64[s]
CustomerID                 str
PaymentMethod              str
OrderStatus                str
dtype: object

In [42]:
Customers["SignupDate"] = pd.to_datetime(
    Customers["SignupDate"]
)

In [44]:
Customers.dtypes

CustomerID                str
CustomerName              str
Gender                    str
Age                     int64
City                      str
Region                    str
SignupDate      datetime64[s]
dtype: object

In [46]:
# Missing value
Customers.isnull().sum()
orders.isnull().sum()
returns.isnull().sum()
products.isnull().sum()
orderdetails.isnull().sum()

OrderDetailID    0
OrderID          0
ProductID        0
Quantity         0
UnitPrice        0
DiscountPct      0
SalesAmount      0
Profit           0
dtype: int64

In [47]:
orderdetails.describe()

           Quantity     UnitPrice   DiscountPct   SalesAmount        Profit
count  12558.000000  12558.000000  12558.000000  12558.000000  12558.000000
mean       2.501752   6272.299570     10.742156  14010.138708   4804.382457
std        1.119501   3461.536155      7.112802  10628.052040   4894.725391
min        1.000000    319.000000      0.000000    239.250000  -2048.000000
25%        2.000000   3416.000000      5.000000   5949.000000   1342.400000
50%        2.000000   6288.000000     10.000000  11210.400000   3215.600000
75%        4.000000   8847.000000     15.000000  20044.800000   6608.400000
max        4.000000  14270.000000     25.000000  57080.000000  30860.000000

In [69]:
df = orders.merge(Customers,on = "CustomerID",how = "left")

In [70]:
df = df.merge(orderdetails,on = "OrderID",how = "inner")

In [78]:

# Rename the remaining _x columns to remove _x
df = df.rename(columns={
    'OrderDetailID_x': 'OrderDetailID',
    'ProductID_x': 'ProductID',
    'Quantity_x': 'Quantity',
    'UnitPrice_x': 'UnitPrice',
    'DiscountPct_x': 'DiscountPct',
    'SalesAmount_x': 'SalesAmount',
    'Profit_x': 'Profit'
})

In [79]:
print("df columns:", df.columns.tolist())
print("products columns:", products.columns.tolist())

df columns: ['OrderID', 'OrderDate', 'CustomerID', 'PaymentMethod', 'OrderStatus', 'CustomerName', 'Gender', 'Age', 'City', 'Region', 'SignupDate', 'OrderDetailID', 'ProductID', 'Quantity', 'UnitPrice', 'DiscountPct', 'SalesAmount', 'Profit']
products columns: ['ProductID', 'ProductName', 'Category', 'CostPrice', 'SellingPrice']

In [82]:
df = df.merge(
    products,
   on = "ProductID",
   how = "left")

In [83]:
df.shape

(12558, 22)

In [84]:
df.head()

,OrderID,OrderDate,CustomerID,PaymentMethod,OrderStatus,CustomerName,Gender,Age,City,Region,...,ProductID,Quantity,UnitPrice,DiscountPct,SalesAmount,Profit,ProductName,Category,CostPrice,SellingPrice
0,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,...,P0014,4,10018.0,15.0,34061.20,12649.20,Mouse,Electronics,5353.0,10018.0
1,O00001,2026-01-19,C0484,UPI,Delivered,Customer_0484,Female,31,Pune,West,...,P0063,3,5568.0,5.0,15868.80,6532.80,Shampoo,Beauty,3112.0,5568.0
2,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,...,P0030,1,10331.0,5.0,9814.45,3909.45,Table Lamp,Home,5905.0,10331.0
3,O00002,2026-02-14,C0450,Credit Card,Delivered,Customer_0450,Female,23,Hyderabad,South,...,P0027,4,4363.0,10.0,15706.80,2006.80,Air Fryer,Home,3425.0,4363.0
4,O00003,2025-11-21,C0523,Credit Card,Delivered,Customer_0523,Female,60,Delhi,North,...,P0040,2,6601.0,5.0,12541.90,4543.90,T-Shirt,Fashion,3999.0,6601.0

In [85]:
df.duplicated().sum()

np.int64(0)

In [88]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'PaymentMethod', 'OrderStatus',
       'CustomerName', 'Gender', 'Age', 'City', 'Region', 'SignupDate',
       'OrderDetailID', 'ProductID', 'Quantity', 'UnitPrice', 'DiscountPct',
       'SalesAmount', 'Profit', 'ProductName', 'Category', 'CostPrice',
       'SellingPrice', 'Year'],
      dtype='str')

In [89]:
df.columns = df.columns.astype("object")

In [90]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'PaymentMethod', 'OrderStatus',
       'CustomerName', 'Gender', 'Age', 'City', 'Region', 'SignupDate',
       'OrderDetailID', 'ProductID', 'Quantity', 'UnitPrice', 'DiscountPct',
       'SalesAmount', 'Profit', 'ProductName', 'Category', 'CostPrice',
       'SellingPrice', 'Year'],
      dtype='object')

In [92]:
df["Year"] = df["OrderDate"].dt.year
df["Month"] = df["OrderDate"].dt.month
df["Monthname"] = df["OrderDate"].dt.month_name()
df["Year Name"] = df["OrderDate"].dt.to_period("M").astype(str)

In [93]:
df["profitmarginPct"] = (
    df["Profit"] / 
    df["SalesAmount"]

)*100

In [94]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12558 entries, 0 to 12557
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          12558 non-null  str
 1   OrderDate        12558 non-null  datetime64[s]
 2   CustomerID       12558 non-null  str
 3   PaymentMethod    12558 non-null  str
 4   OrderStatus      12558 non-null  str
 5   CustomerName     12558 non-null  str
 6   Gender           12558 non-null  str
 7   Age              12558 non-null  int64
 8   City             12558 non-null  str
 9   Region           12558 non-null  str
 10  SignupDate       12558 non-null  datetime64[s]
 11  OrderDetailID    12558 non-null  str
 12  ProductID        12558 non-null  str
 13  Quantity         12558 non-null  int64
 14  UnitPrice        12558 non-null  float64
 15  DiscountPct      12558 non-null  float64
 16  SalesAmount      12558 non-null  float64
 17  Profit           12558 non-null  float64
 18  ProductName      12558 non-null  str
 19  Category         12558 non-null  str
 20  CostPrice        12558 non-null  float64
 21  SellingPrice     12558 non-null  float64
 22  Year             12558 non-null  int32
 23  Month            12558 non-null  int32
 24  Monthname        12558 non-null  str
 25  Year Name        12558 non-null  str
 26  profitmarginPct  12558 non-null  float64
dtypes: datetime64[s](2), float64(7), int32(2), int64(2), str(14)
memory usage: 3.7 MB

In [96]:
df.isnull()

,OrderID,OrderDate,CustomerID,PaymentMethod,OrderStatus,CustomerName,Gender,Age,City,Region,...,Profit,ProductName,Category,CostPrice,SellingPrice,Year,Month,Monthname,Year Name,profitmarginPct
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12553,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12554,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12555,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12556,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12557,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [98]:
df.to_csv(
    "ecommerce_clean_data.csv",
    index=False
)